# Generated by Django 4.2.2 on 2023-12-14 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_check_in', models.DateField()),
                ('book_check_out', models.DateField()),
                ('book_guest_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_score', models.FloatField()),
                ('review_content', models.TextField()),
                ('review_created_at', models.DateTimeField(auto_now_add=True)),
                ('review_updated_at', models.DateTimeField(auto_now=True)),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('room_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('room_address', models.CharField(max_length=50)),
                ('room_des', models.TextField()),
                ('room_max', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_created_at', models.DateTimeField(auto_now_add=True)),
                ('room_updated_at', models.DateTimeField(auto_now=True)),
                ('room_booked', models.ManyToManyField(null=True, related_name='user_room', through='rooms.Book', to=settings.AUTH_USER_MODEL)),
                ('room_host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.host')),
                ('room_option', models.ManyToManyField(blank=True, related_name='options_room', to='rooms.option')),
                ('room_reviews', models.ManyToManyField(null=True, related_name='review_room', through='rooms.Review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_room', to='rooms.type'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviewed', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
