# Generated by Django 4.2.2 on 2023-12-17 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_like_users',
            field=models.ManyToManyField(related_name='like_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
